spring:
  datasource:
    url: jdbc:mysql://localhost:3306/formare_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
    show-sql: true
#
#server:
#  error:
#    include-binding-errors: always
#    include-message: always
#  port: 8081
